### ISSUE TITLE
Failure at startup due to cljs.reader.push_back_reader undefined

### ISSUE THREAD

**Issue by Bill** [Unrepl/unravel#17]
Following instructions in [_Launching a Socket REPL_](https://github.com/Unrepl/unravel#launching-a-socket-repl) I boot a socket REPL:

```sh
Bills-MacBook-Air:~ Bill$ boot --version
#http://boot-clj.com
#Sun Aug 20 09:44:04 PDT 2017
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.9.0-alpha17
BOOT_VERSION=2.7.2
Bills-MacBook-Air:~ Bill$ boot socket-server --port 50505 wait
Socket server started on port 50505 on host 127.0.0.1.
```

…and then run `unravel` (in a second terminal)

```sh
Bills-MacBook-Air:~ Bill$ unravel --version
Unravel 0.2.2 (Lumo 1.7.0)
Bills-MacBook-Air:~ Bill$ unravel localhost 50505
evalmachine.<anonymous>:22
var reader = cljs.reader.push_back_reader.call(null,s);
                                         ^

TypeError: Cannot read property 'call' of undefined
    at unravel$lisp$safe_read_string (evalmachine.<anonymous>:22:42)
    at Transform._transform (evalmachine.<anonymous>:56:60)
    at Transform._read (_stream_transform.js:186:10)
    at Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:385:12)
    at writeOrBuffer (_stream_writable.js:371:5)
    at Transform.Writable.write (_stream_writable.js:288:11)
    at Transform.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at Transform.emit (events.js:210:7)
```

Same error `BOOT_CLOJURE_VERSION=1.8.0`. Same error if I launch the socket REPL with:

```sh
boot -i "(do (require 'clojure.core.server) (clojure.core.server/start-server {:port 50505 :name :repl :accept 'clojure.core.server/repl}))" wait
```

**Comment by pesterhazy** [comment]
Thanks for the report, I can reproduce locally. The error is caused by the release of lumo 1.7.0, which ships a newer version of clojurescript. Looks like we made use of the internal part of cljs.reader's API.

Probably best to use cljs.tools.reader (or cljs.tools.reader.edn) instead. I've started a PR but it doesn't work yet: https://github.com/Unrepl/unravel/pull/18

I'll have to look into differences between cljs.tools.reader and cljs.reader.
