### ISSUE TITLE
`source` throws

### ISSUE THREAD

**Issue by pesterhazy** [Unrepl/unravel#41]
```
user=> (source source)
net.js:692
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:692:11)
    at evalmachine.<anonymous>:238:16
    at cljs.core.MultiFn.e (<embedded>:1846:390)
    at cljs.core.MultiFn.a [as call] (<embedded>:1863:55)
    at Function.<anonymous> (evalmachine.<anonymous>:1334:29)
    at Function.cljs.core.apply_to_simple.cljs$core$IFn$_invoke$arity$5 (<embedded>:773:165)
    at Function.cljs.core.apply_to_simple.cljs$core$IFn$_invoke$arity$4 (<embedded>:772:199)
    at Function.cljs.core.apply_to_simple.cljs$core$IFn$_invoke$arity$3 (<embedded>:771:193)
    at Function.cljs.core.apply.cljs$core$IFn$_invoke$arity$3 (<embedded>:784:304)
    at cljs.core.apply (<embedded>:781:171)
    at evalmachine.<anonymous>:775:92
    at G__295__delegate (evalmachine.<anonymous>:794:3)
    at G__295 (evalmachine.<anonymous>:805:25)
    at Transform.<anonymous> (evalmachine.<anonymous>:1339:11)
    at emitOne (events.js:115:13)
    at Transform.emit (events.js:210:7)
```

**Comment by pesterhazy** [comment]
Fixed in master
